config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :business_profiles do
    member do
      get :join
      delete :leave
    end
  end
  resources :profiles
  devise_for :users, :controllers => { :registrations => "registrations" }
  get 'admin', to: 'admin#index'

  get 'home/index'

  root 'home#index'

end

app/models/business_profile.rb
# == Schema Information
#
# Table name: business_profiles
#
#  id           :integer          not null, primary key
#  name         :string
#  logo         :string
#  description  :text
#  head_count   :integer
#  website_link :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  slug         :string
#

class BusinessProfile < ActiveRecord::Base
  has_many :business_users
  has_many :events
  has_many :users, through: :business_users

  acts_as_taggable

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/business_profiles_controller.rb
class BusinessProfilesController < ApplicationController
  before_action :set_business_profile, only: [:join, :leave, :show, :edit, :update, :destroy]

  def join
    @business_profile.users << current_user
    redirect_to :back
  end

  def leave
    @business_profile.users.delete(current_user)
    redirect_to :back
  end

  # GET /business_profiles
  # GET /business_profiles.json
  def index
    if params[:tag]
      @tag = ActsAsTaggableOn::Tag.find_by(name: params[:tag])
      @business_profiles = BusinessProfile.tagged_with(params[:tag])
    else
      @business_profiles = BusinessProfile.all
    end
  end

  # GET /business_profiles/1
  # GET /business_profiles/1.json
  def show
    @users = @business_profile.users
    @events = @business_profile.events.future_events.chron_order.limit(3)
  end

  # GET /business_profiles/new
  def new
    @business_profile = BusinessProfile.new
  end

  # GET /business_profiles/1/edit
  def edit
  end

  # POST /business_profiles
  # POST /business_profiles.json
  def create
    @business_profile = BusinessProfile.new(business_profile_params)
    @business_profile.users << current_user

    respond_to do |format|
      if @business_profile.save
        format.html { redirect_to @business_profile, notice: 'Business profile was successfully created.' }
        format.json { render :show, status: :created, location: @business_profile }
      else
        format.html { render :new }
        format.json { render json: @business_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business_profiles/1
  # PATCH/PUT /business_profiles/1.json
  def update
    @business_profile.slug = nil
    respond_to do |format|
      if @business_profile.update(business_profile_params)
        format.html { redirect_to @business_profile, notice: 'Business profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_profile }
      else
        format.html { render :edit }
        format.json { render json: @business_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_profiles/1
  # DELETE /business_profiles/1.json
  def destroy
    @business_profile.destroy
    respond_to do |format|
      format.html { redirect_to business_profiles_url, notice: 'Business profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_profile
      @business_profile = BusinessProfile.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_profile_params
      params.require(:business_profile).permit(:name, :logo, :description, :head_count, :website_link, :tag_list)
    end
end

app/views/business_profiles/_form.html.erb
<%= simple_form_for(@business_profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :logo %>
    <%= f.input :description %>
    <%= f.input :head_count %>
    <%= f.input :website_link %>
    <%= f.input :tag_list %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/business_profiles/edit.html.erb
<h1>Editing Business Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @business_profile %> |
<%= link_to 'Back', business_profiles_path %>

app/views/business_profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Business Profiles <%= "tagged with " + params[:tag] + " (" + @tag.taggings_count.to_s + ")" if params[:tag] %> </h1>
<%= link_to 'Clear filter (all profiles)', business_profiles_path, class: 'btn btn-warning' %><br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Logo</th>
      <th>Description</th>
      <th>Head count</th>
      <th>Website link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @business_profiles.each do |business_profile| %>
      <tr>
        <td><%= business_profile.name %></td>
        <td><%= business_profile.logo %></td>
        <td><%= business_profile.description %></td>
        <td><%= business_profile.head_count %></td>
        <td><%= business_profile.website_link %></td>
        <td><%= link_to 'Show', business_profile %></td>
        <td><%= link_to 'Edit', edit_business_profile_path(business_profile) %></td>
        <td><%= link_to 'Destroy', business_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business profile', new_business_profile_path %>

app/views/business_profiles/new.html.erb
<h1>New Business Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', business_profiles_path %>

app/views/business_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @business_profile.name %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @business_profile.logo %>
</p>

<p>
  <strong>Description:</strong>
  <%= @business_profile.description %>
</p>

<p>
  <strong>Head count:</strong>
  <%= @business_profile.users.count %>
</p>

<p>
  <strong>Website link:</strong>
  <%= @business_profile.website_link %>
</p>

<h3>Tagged with:</h3>
<ul>
  <% @business_profile.tags.each do |tag| %>
    <li><%= link_to tag, business_profiles_path(tag: tag.name) %></li>
<% end %>
</ul>

<h3>People in this business</h3>
<% @users.each do |user| %>
  <p><%= user.profile.name %></p>
  <% end %>



<% if @business_profile.users.include?(current_user) %>
  <%= link_to "I don't work here", leave_business_profile_path, method: :delete, class: 'btn btn-danger' %>
<% else %>
  <%= link_to "I work here", join_business_profile_path, class: 'btn btn-primary' %>
<% end %>

<%= link_to 'Edit', edit_business_profile_path(@business_profile) %> |
<%= link_to 'Back', business_profiles_path %>